### ISSUE TITLE
Unused stubs causes errors in subsequent tests

### ISSUE THREAD

**Issue by ombre42** [kaste/pytest-mockito#1]
If you have a class with say 10 tests where the class is using the unstub fixture, then, if any test causes `verifyStubbedInvocationsAreUsed` to fail by not using a stub, then that unused stub is not removed and causes errors in the teardown of all subsequent tests. This is distracting and it takes longer to find the problem due to pytest's verbosity. Calling `unstub` as test setup is also undesirable.

This is resolved by still calling `unstub` even when `verifyStubbedInvocationsAreUsed` fails.
Either of the following fixes it. Not sure which one is better.

```
@pytest.fixture
def unstub():
    from mockito import unstub, verifyStubbedInvocationsAreUsed, VerificationError
    yield unstub

    try:
        verifyStubbedInvocationsAreUsed()
    except VerificationError as e:
        unstub()
        raise e
    else:
        unstub()
```

```
@pytest.fixture
def unstub():
    from mockito import unstub, verifyStubbedInvocationsAreUsed
    yield unstub

    try:
        verifyStubbedInvocationsAreUsed()
    finally:
        unstub()

**Comment by kaste** [comment]
Thanks for reporting. Another way to fix this is: https://github.com/kaste/pytest-mockito/blob/ba361b2e4e42fdf24be5c1883bd2e3c95636488f/pytest_mockito/plugin.py#L5-L16
This is so that `pytest` stays responsible for tearing down any fixtures.

Released as `0.0.4`

**Comment by ombre42** [comment]
Thanks for fixing this so fast! Tested out the new changes and works as expected.
Occasionally stubs are used just to meet the dependencies of the code under test and verifying they are used means depending heavily on implementation details. I may be tempted to use `unstub_` occasionally :)

**Comment by ombre42** [comment]
@kaste 0.0.4 was never released to fix this issue. The latest version in PyPI and on GitHub is 0.0.3. Could you please do the release?
Thanks!

**Comment by kaste** [comment]
Jesus, I forgot to push the tags.
